# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 01:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 1, 40, 16, 901097)),
        ),
    ]
