# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
