# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transductormodel',
            name='measurements_type',
            field=models.CharField(default='EnergyMeasurements', max_length=50),
            preserve_default=False,
        ),
    ]
