# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0002_auto_20160927_1527'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='energymeasurements',
            managers=[
                ('mng_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='measurements',
            name='collection_date',
            field=models.DateField(auto_now=True, verbose_name='date published'),
        ),
    ]
