# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0003_auto_20160927_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='working_correctly',
            field=models.BooleanField(default=True),
        ),
    ]
