# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energytransductor',
            options={'permissions': (('can_view_transductors', 'Can view Transductors Page'),)},
        ),
    ]
