# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=b'staff status'),
        ),
    ]
