# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 20:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransductorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('internet_protocol', models.CharField(max_length=50)),
                ('serial_protocol', models.CharField(max_length=50)),
                ('register_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='energytransductor',
            name='data_collection',
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_reader.TransductorInfo'),
            preserve_default=False,
        ),
    ]
