# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 12:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True,
                 serialize=False,
                 verbose_name='ID')),
                ('status', models.BooleanField()),
                ('description', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2016, 11, 10, 12, 24, 46, 789844))),
                ('local', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_check_alerts', 'Can Check Alerts'),),
            },
        ),
    ]
