# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20161111_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 11, 21, 20, 18, 995876)),
        ),
    ]
